image:
  server: http://dev6668886666999998888.com
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 192.168.142.134
    virtual-host: /java1907
    username: java1907
    password: 123
