image:
  server: http://dev6668886666999998888.com
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 192.168.15.129
    virtual-host: test
    username: guest
    password: guest
