spring:
  application:
    name: product-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
server:
  port: 8080
